name: HereComesTheGoodNews

on:
  schedule:
    - cron: "30 1-11/2 * * 1-5"
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests selenium

      - name: Run push script
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          ZJUAM_ACCOUNT: ${{ secrets.ZJUAM_ACCOUNT }}
          ZJUAM_PASSWORD: ${{ secrets.ZJUAM_PASSWORD }}
        run: |
          python HereComesTheGoodNews.py
      - name: Commit and push output file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
          git add last_result.json
          git commit -m "Update last_result.json [auto]" || echo "No changes to commit"
          git push

